### ISSUE TITLE
AMR criteria using HeatRelease

### ISSUE THREAD

**Issue by mameehan5** [AMReX-Combustion/PeleLMeX#102]
Hi all,

I am looking to use HeatRelease as a quantity to refine the grid on, and looking through the tutorials, it looks like the [swirl case](https://github.com/AMReX-Combustion/PeleLMeX/tree/dd0f07593530499f3dfcf0c7309b46ed28257efd/Exec/Cases/SwirlFlowWallInteractions) does exactly this. However, when I try to do this, I get an error
```
amrex::Error::42::PeleLM::taggingSetup(): unknown variable field for criteria HR
```
Is HeatRelease a supported tagging field? If not, is this something you want to include in the future?

Thanks!

**Comment by esclapez** [comment]
Hi Mike,

HeatRelease is indeed missing as a derived. I've got a PR coming with a couple of things, I'll append this to it.

Lucas

**Comment by mameehan5** [comment]
Got it, thanks Lucas!

**Comment by esclapez** [comment]
That should be fixed when #105 is merged. Note that HeatRelease is not directly available during generation of the initial grid, such that upon init fine grids will not be triggered by HeatRelease. At subsequent regrid operations (once the code as been through the advance function), then tagging on HeatRelease will kick in.

**Comment by mameehan5** [comment]
Got it! Thanks for the heads up. I appreciate you checking this out so quickly.

**Comment by esclapez** [comment]
It pushes me to stop procrastinating !
