### ISSUE TITLE
OMP problem?

### ISSUE THREAD

**Issue by jckim1201** [AMReX-Combustion/PeleLMeX#199]
Hi everyone,

I'm trying to solve the FlameSheet problem, which is a RegTest within PeleLMeX. I have a problem that when I apply the OMP option of GNUmakefile, the problem does not converge and hangs with errors. I don't have any problems when using MPI only. Is there a problem with the OMP option?

The compilation options are as follows

# Compilation
COMP            = gnu
USE_MPI         = TRUE
USE_OMP         = TRUE
USE_CUDA        = FALSE
USE_HIP         = FALSE

**Comment by baperry2** [comment]
OpenMP is currently not supported with the CVODE chemistry integrator. I'd recommend just sticking with pure MPI for parallelism on CPU, we don't expect there would be big gains for MPI+OpenMP in most cases anyway (the explicit RK chemistry integrator does work with OpenMP, but CVODE is much better than that).

**Comment by jckim1201** [comment]
Thank you.
