### ISSUE TITLE
Question about combustion simulation

### ISSUE THREAD

**Issue by CAIROCharlie** [AMReX-Combustion/PeleLMeX#213]
Hello!
May I ask how to add radiative heat loss in combustion simulation?

Thank you.

**Comment by wjge** [comment]
We are still merging/testing the radiation module.
It is ready to build and run.  
https://github.com/AMReX-Combustion/PeleRad
If you need to add radiation to your case now, I can push the latest to my fork of PeleLMeX.

**Comment by CAIROCharlie** [comment]
Thank you very much for your reply!!!
I want to add radiation to my case.But I don't know how to add PeleRad to the case of PeleLMeX.

**Comment by wjge** [comment]
@CAIROCharlie Hi, I added a script (https://github.com/wjge/PeleMP/blob/PR_radiation/Exec/JetTests/PeleLMeX/xburner_rad/script/build_Frontier.sh) to show how to build the latest PeleLMeX with radiation. The script is for AMD GPU (on the OLCF Frontier), but you shall be able to modify it to build and run your own simulation on most architectures supported by Pele.

**Comment by CAIROCharlie** [comment]
Thank you very much! I will try it!
