### ISSUE TITLE
Reading input data from HDF5 file

### ISSUE THREAD

**Issue by bazharz** [AMReX-Combustion/PeleLMeX#221]
Is it possible to read input data from hdf5 file?

**Comment by baperry2** [comment]
PeleLMeX does not support reading input data from hdf5 files. When loading init data from a plt file, AMReX native format plt files must be used.

**Comment by esclapez** [comment]
The main reason being that there is currently no support for reading HDF5 AMR data in AMReX.

**Comment by baperry2** [comment]
Closing this as implementation is not planned and would be dependent on AMReX development
