### ISSUE TITLE
peleLM.isothermal_EB = 1 causes CUDA error 700 - illegal memory access was encountered !!!

### ISSUE THREAD

**Issue by taaresh1** [AMReX-Combustion/PeleLMeX#237]
Hello, I am able to run a low Mach case with a fairly complex geometry with EB on CPUs. However, the same setup doesn't run on GPUs. It complains of illegal memory access. My case has isothermal walls.
After ruling out all possibilities, I have narrowed down the issue: switching the flag to peleLM.isothermal_EB = 0 runs seamlessly, but setting it to 1 results in the above mentioned error. 

The Backtrace file points to PeleLMUtils.cpp (line 333 - function - intFluxDivergenceLevelEB) where this issue may have arisen first. 

Is there a fix for this? Looking forward to some help on this.

Thanks!

Taaresh

**Comment by baperry2** [comment]
Ok, I was able to reproduce with the `EB_BackwardStepFlame` in 2D running on Eagle GPUs. Definitely a bug, will have to investigate

**Comment by taaresh1** [comment]
Thanks for looking into it, Bruce! Looking forward to the fix.
