### ISSUE TITLE
Add the diffusion coefficients of each species in the PLT directories.

### ISSUE THREAD

**Issue by bazharz** [AMReX-Combustion/PeleLMeX#310]
I want to store the diffusion coefficients of each species like the mass fractions and the production rate for each species because I need them in the PeleAnalysis part to perform calculations.

I tried to see how I_R and Y(species) are stored, but I can't find the arrays where the diffusion coefficients are stored.

Could you help me add the diffusion coefficients in the output?

Thank you in advance.

**Comment by baperry2** [comment]
As described in the [documentation](https://amrex-combustion.github.io/PeleLMeX/manual/html/LMeXControls.html#io-parameters) you can add any available derived variable to your plot files, but there is a slight error in the documentation on [derived variables](https://amrex-combustion.github.io/PeleLMeX/manual/html/LMeXControls.html#pelelmex-derived-variables) as the name for the diffusion coefficients is `diffcoeff` not `diffcoeffs`.

Adding this to your input file should work for you:
`amr.derive_plot_vars = diffcoeff`

**Comment by bazharz** [comment]
Thank you for the clarification. I've updated the input file with "amr.derive_plot_vars = diffcoeff" as suggested, and it works perfectly.
