### ISSUE TITLE
pelelm.incompressible flag segfaults

### ISSUE THREAD

**Issue by ThomasHowarth** [AMReX-Combustion/PeleLMeX#340]
Hi,
If I run with the incompressible flag switched on, the code segfaults. I tracked it down to the line in the Utils that tries to get the reactions MF without a flag check (e.g. m_do_react or m_incompressible, referenced below). I could fix it and put in a pull request but figured someone could add this quick fix without needing a full pull request.

https://github.com/AMReX-Combustion/PeleLMeX/blob/2b95bc8df51829d5f81a48bc7a9b060fc7fe8545/Source/PeleLMeX_Utils.cpp#L971

Thomas

**Comment by baperry2** [comment]
@ThomasHowarth good catch. Thanks for finding this and tracking down the source of the error. I think a single check on `m_do_react` should resolve the issue for both incompressible and nonreacting but compressible flows. 

Currently all changes, whether a single line or a whole new capability, must be made through a PR. So please do submit a PR with the fix if you are willing! The PR should go through easily for something like this.
