### ISSUE TITLE
amrex::Abort::0::MLMGBndry::setBoxBC: Unknown LinOpBCType !!! SIGABRT

### ISSUE THREAD

**Issue by sachdevakunal** [AMReX-Combustion/PeleLMeX#377]
Hello. I am trying to replicate the "Non-reacting flow past a cylinder" tutorial provided by amrex-combustion under PeleLMeX. I did everything as specified in the tutorial, the only change that I made was turning off the MPI, by doing USE_MPI = FALSE in GNUmakefile.
When I try to run the case by giving the command "./PeleLMeX2d.gnu.ex input.2d-Re500", it gives this error -

Doing initial projection(s)

amrex::Abort::0::MLMGBndry::setBoxBC: Unknown LinOpBCType !!!
SIGABRT
See Backtrace.0 file for details

Can you please tell me where am I going wrong?

Thank you for your time.

**Comment by baperry2** [comment]
Can you confirm that you are using the latest version of of PeleLMeX and the default version of AMReX that it ships with via `Submodules/PelePhysics/Submodules/amrex`? At the top of the output from you run, you should see output with the Git hashes that exactly matches:

```
 ================= Build infos =================
 PeleLMeX    git hash: v23.11-54-gf91b9b8
 AMReX       git hash: 24.05-1-g1735fd5c6
 PelePhysics git hash: v23.03-107-g1bea1bfe
 AMReX-Hydro git hash: 24.04
 ===============================================
```

I am able to run the `input.2d-Re500` case with these versions. If all your versions match, I'm not sure what would be causing this failure, but let us know what system you are running on and what compiler you are using if you are failing with these versions.

**Comment by sachdevakunal** [comment]
I cloned the github repo 2 days ago, and there have not been any commits since then, so I am assuming that all the versions are latest. 
However, when I run the code, I am getting these Git hashes, which are similar but not exactly the same:

================= Build infos =================
 PeleLMeX    git hash: v23.11-54-gf91b9b8-dirty
 AMReX       git hash: 1735fd5
 PelePhysics git hash: 1bea1bf
 AMReX-Hydro git hash: 24.04

Any suggestions on what should I do next?

**Comment by baperry2** [comment]
Yeah, the git hashes match so it looks like all your versions are correct/up to date. Run git status / git diff to double check that no files have been inadvertantly changed other than turning off MPI in the GNUmakefile, but you should be good with those versions.

Please mention what compiler (and its version) you are using and what system you are running on. If you have access to a different system, try doing a fresh download and building and running on that system.

**Comment by sachdevakunal** [comment]
It's working now. In the tutorial, it was given that 

#----------------------DOMAIN DEFINITION------------------------
geometry.is_periodic = 0 0             # Periodicity in each direction: 0 => no, 1 => yes
geometry.coord_sys   = 0               # 0 => cart, 1 => RZ

But actually, it should be 

#----------------------DOMAIN DEFINITION------------------------
geometry.is_periodic = 0 1             # Periodicity in each direction: 0 => no, 1 => yes
geometry.coord_sys   = 0               # 0 => cart, 1 => RZ

I was changing the geometry.is_periodic to 0 0, and that was causing the issue. I think there is a typo in the tutorial, but anyway, thanks a lot for your help.
